2012-12-26 21:31:00,361 - handler.py:21 - handler - ------------start--------------------

2012-12-26 21:31:00,362 - handler.py:31 - handler - POST on /scgi-bin/handler.py?signature=840e8ee35ef65dd598f1c5f249fa213801fdf6d4&timestamp=1356517202&nonce=1355917928
2012-12-26 21:31:00,363 - handler.py:55 - handler - raw:<xml><ToUserName><![CDATA[gh_1ff87fe87f88]]></ToUserName>
<FromUserName><![CDATA[oaEn2jhk1nCu9VREAmtTDufQd5kw]]></FromUserName>
<CreateTime>1356344005</CreateTime>
<MsgType><![CDATA[text]]></MsgType>
<Content><![CDATA[Northen JiaoTong ]></Content>
</xml>
2012-12-26 21:31:41,440 - handler.py:21 - handler - ------------start--------------------

2012-12-26 21:31:41,441 - handler.py:31 - handler - POST on /scgi-bin/handler.py?signature=840e8ee35ef65dd598f1c5f249fa213801fdf6d4&timestamp=1356517202&nonce=1355917928
2012-12-26 21:31:41,441 - handler.py:55 - handler - raw:<xml><ToUserName><![CDATA[gh_1ff87fe87f88]]></ToUserName>
<FromUserName><![CDATA[oaEn2jhk1nCu9VREAmtTDufQd5kw]]></FromUserName>
<CreateTime>1356344005</CreateTime>
<MsgType><![CDATA[text]]></MsgType>
<Content><![CDATA[Northen JiaoTong ]></Content>
</xml>
2012-12-26 21:32:15,899 - handler.py:21 - handler - ------------start--------------------

2012-12-26 21:32:15,899 - handler.py:31 - handler - POST on /scgi-bin/handler.py?signature=840e8ee35ef65dd598f1c5f249fa213801fdf6d4&timestamp=1356517202&nonce=1355917928
2012-12-26 21:32:15,899 - handler.py:55 - handler - raw:<xml><ToUserName><![CDATA[gh_1ff87fe87f88]]></ToUserName>
<FromUserName><![CDATA[oaEn2jhk1nCu9VREAmtTDufQd5kw]]></FromUserName>
<CreateTime>1356344005</CreateTime>
<MsgType><![CDATA[text]]></MsgType>
<Content><![CDATA[Northen JiaoTong ]></Content>
</xml>
2012-12-26 21:32:54,161 - handler.py:21 - handler - ------------start--------------------

2012-12-26 21:32:54,161 - handler.py:31 - handler - POST on /scgi-bin/handler.py?signature=840e8ee35ef65dd598f1c5f249fa213801fdf6d4&timestamp=1356517202&nonce=1355917928
2012-12-26 21:32:54,161 - handler.py:55 - handler - raw:<xml><ToUserName><![CDATA[gh_1ff87fe87f88]]></ToUserName>
<FromUserName><![CDATA[oaEn2jhk1nCu9VREAmtTDufQd5kw]]></FromUserName>
<CreateTime>1356344005</CreateTime>
<MsgType><![CDATA[text]]></MsgType>
<Content><![CDATA[Northen JiaoTong ]]></Content>
</xml>
2012-12-26 21:32:54,287 - handler.py:78 - handler - exception in on_post
Traceback (most recent call last):
  File "/Users/user/Documents/workspace/KuaiSou/ks_cgi/handler.py", line 64, in on_post
    Content=google(Content)
  File "/Users/user/Documents/workspace/KuaiSou/ks_cgi/handler.py", line 47, in google
    search_results = urllib.urlopen(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 84, in urlopen
    return opener.open(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 205, in open
    return getattr(self, name)(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 342, in open_http
    h.endheaders(data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 951, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 811, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 773, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 754, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 553, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
IOError: [Errno socket error] [Errno 8] nodename nor servname provided, or not known
2012-12-26 21:32:54,289 - handler.py:108 - handler - ------------end--------------------


2012-12-26 21:34:20,747 - handler.py:21 - handler - ------------start--------------------

2012-12-26 21:34:20,747 - handler.py:31 - handler - POST on /scgi-bin/handler.py?signature=840e8ee35ef65dd598f1c5f249fa213801fdf6d4&timestamp=1356517202&nonce=1355917928
2012-12-26 21:34:20,747 - handler.py:55 - handler - raw:<xml><ToUserName><![CDATA[gh_1ff87fe87f88]]></ToUserName>
<FromUserName><![CDATA[oaEn2jhk1nCu9VREAmtTDufQd5kw]]></FromUserName>
<CreateTime>1356344005</CreateTime>
<MsgType><![CDATA[text]]></MsgType>
<Content><![CDATA[Northen JiaoTong ]]></Content>
</xml>
2012-12-26 21:34:20,882 - handler.py:78 - handler - exception in on_post
Traceback (most recent call last):
  File "/Users/user/Documents/workspace/KuaiSou/ks_cgi/handler.py", line 64, in on_post
    Content=google(Content)
  File "/Users/user/Documents/workspace/KuaiSou/ks_cgi/handler.py", line 47, in google
    search_results = urllib.urlopen(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 84, in urlopen
    return opener.open(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 205, in open
    return getattr(self, name)(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 342, in open_http
    h.endheaders(data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 951, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 811, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 773, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 754, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 553, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
IOError: [Errno socket error] [Errno 8] nodename nor servname provided, or not known
2012-12-26 21:34:20,883 - handler.py:108 - handler - ------------end--------------------


2012-12-26 21:34:38,177 - handler.py:21 - handler - ------------start--------------------

2012-12-26 21:34:38,177 - handler.py:31 - handler - POST on /scgi-bin/handler.py?signature=840e8ee35ef65dd598f1c5f249fa213801fdf6d4&timestamp=1356517202&nonce=1355917928
2012-12-26 21:34:38,177 - handler.py:55 - handler - raw:<xml><ToUserName><![CDATA[gh_1ff87fe87f88]]></ToUserName>
<FromUserName><![CDATA[oaEn2jhk1nCu9VREAmtTDufQd5kw]]></FromUserName>
<CreateTime>1356344005</CreateTime>
<MsgType><![CDATA[text]]></MsgType>
<Content><![CDATA[Northen JiaoTong]]></Content>
</xml>
2012-12-26 21:34:38,340 - handler.py:78 - handler - exception in on_post
Traceback (most recent call last):
  File "/Users/user/Documents/workspace/KuaiSou/ks_cgi/handler.py", line 64, in on_post
    Content=google(Content)
  File "/Users/user/Documents/workspace/KuaiSou/ks_cgi/handler.py", line 47, in google
    search_results = urllib.urlopen(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 84, in urlopen
    return opener.open(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 205, in open
    return getattr(self, name)(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 342, in open_http
    h.endheaders(data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 951, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 811, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 773, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 754, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 553, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
IOError: [Errno socket error] [Errno 8] nodename nor servname provided, or not known
2012-12-26 21:34:38,342 - handler.py:108 - handler - ------------end--------------------


2012-12-26 21:57:52,535 - handler.py:21 - handler - ------------start--------------------

2012-12-26 21:57:52,535 - handler.py:31 - handler - POST on /scgi-bin/handler.py?signature=840e8ee35ef65dd598f1c5f249fa213801fdf6d4&timestamp=1356517202&nonce=1355917928
2012-12-26 21:57:52,535 - handler.py:55 - handler - raw:<xml><ToUserName><![CDATA[gh_1ff87fe87f88]]></ToUserName>
<FromUserName><![CDATA[oaEn2jhk1nCu9VREAmtTDufQd5kw]]></FromUserName>
<CreateTime>1356344005</CreateTime>
<MsgType><![CDATA[text]]></MsgType>
<Content><![CDATA[Northen JiaoTong]]></Content>
</xml>
2012-12-26 21:57:52,965 - handler.py:78 - handler - exception in on_post
Traceback (most recent call last):
  File "/Users/user/Documents/workspace/KuaiSou/ks_cgi/handler.py", line 64, in on_post
    Content=google(Content)
  File "/Users/user/Documents/workspace/KuaiSou/ks_cgi/handler.py", line 47, in google
    search_results = urllib.urlopen(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 84, in urlopen
    return opener.open(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 205, in open
    return getattr(self, name)(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 342, in open_http
    h.endheaders(data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 951, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 811, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 773, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 754, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 553, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
IOError: [Errno socket error] [Errno 8] nodename nor servname provided, or not known
2012-12-26 21:57:52,967 - handler.py:108 - handler - ------------end--------------------


2012-12-26 21:58:04,254 - handler.py:21 - handler - ------------start--------------------

2012-12-26 21:58:04,254 - handler.py:31 - handler - POST on /scgi-bin/handler.py?signature=840e8ee35ef65dd598f1c5f249fa213801fdf6d4&timestamp=1356517202&nonce=1355917928
2012-12-26 21:58:04,254 - handler.py:55 - handler - raw:<xml><ToUserName><![CDATA[gh_1ff87fe87f88]]></ToUserName>
<FromUserName><![CDATA[oaEn2jhk1nCu9VREAmtTDufQd5kw]]></FromUserName>
<CreateTime>1356344005</CreateTime>
<MsgType><![CDATA[text]]></MsgType>
<Content><![CDATA[Northen JiaoTong]]></Content>
</xml>
2012-12-26 21:58:04,293 - handler.py:78 - handler - exception in on_post
Traceback (most recent call last):
  File "/Users/user/Documents/workspace/KuaiSou/ks_cgi/handler.py", line 64, in on_post
    Content=google(Content)
  File "/Users/user/Documents/workspace/KuaiSou/ks_cgi/handler.py", line 47, in google
    search_results = urllib.urlopen(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 84, in urlopen
    return opener.open(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 205, in open
    return getattr(self, name)(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 342, in open_http
    h.endheaders(data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 951, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 811, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 773, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 754, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 553, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
IOError: [Errno socket error] [Errno 8] nodename nor servname provided, or not known
2012-12-26 21:58:04,295 - handler.py:108 - handler - ------------end--------------------


2012-12-26 21:59:40,361 - handler.py:21 - handler - ------------start--------------------

2012-12-26 21:59:40,361 - handler.py:31 - handler - POST on /scgi-bin/handler.py?signature=840e8ee35ef65dd598f1c5f249fa213801fdf6d4&timestamp=1356517202&nonce=1355917928
2012-12-26 21:59:40,361 - handler.py:55 - handler - raw:<xml><ToUserName><![CDATA[gh_1ff87fe87f88]]></ToUserName>
<FromUserName><![CDATA[oaEn2jhk1nCu9VREAmtTDufQd5kw]]></FromUserName>
<CreateTime>1356344005</CreateTime>
<MsgType><![CDATA[text]]></MsgType>
<Content><![CDATA[Northen JiaoTong]]></Content>
</xml>
2012-12-26 21:59:40,390 - handler.py:46 - handler - url:http://ajax.googleapis.com/ajax/services/search/web?v=1.0&q=Northen+JiaoTong&rsz=small 
2012-12-26 21:59:40,822 - handler.py:78 - handler - exception in on_post
Traceback (most recent call last):
  File "/Users/user/Documents/workspace/KuaiSou/ks_cgi/handler.py", line 64, in on_post
    Content=google(Content)
  File "/Users/user/Documents/workspace/KuaiSou/ks_cgi/handler.py", line 47, in google
    search_results = urllib.urlopen(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 84, in urlopen
    return opener.open(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 205, in open
    return getattr(self, name)(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 342, in open_http
    h.endheaders(data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 951, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 811, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 773, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 754, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 553, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
IOError: [Errno socket error] [Errno 8] nodename nor servname provided, or not known
2012-12-26 21:59:40,824 - handler.py:108 - handler - ------------end--------------------


2012-12-26 22:02:20,183 - handler.py:21 - handler - ------------start--------------------

2012-12-26 22:02:20,184 - handler.py:31 - handler - POST on /scgi-bin/handler.py?signature=840e8ee35ef65dd598f1c5f249fa213801fdf6d4&timestamp=1356517202&nonce=1355917928
2012-12-26 22:02:20,184 - handler.py:55 - handler - raw:<xml><ToUserName><![CDATA[gh_1ff87fe87f88]]></ToUserName>
<FromUserName><![CDATA[oaEn2jhk1nCu9VREAmtTDufQd5kw]]></FromUserName>
<CreateTime>1356344005</CreateTime>
<MsgType><![CDATA[text]]></MsgType>
<Content><![CDATA[Northen JiaoTong]]></Content>
</xml>
2012-12-26 22:02:20,216 - handler.py:46 - handler - url:http://ajax.googleapis.com/ajax/services/search/web?v=1.0&q=Northen+JiaoTong&rsz=small 
2012-12-26 22:02:20,266 - handler.py:78 - handler - exception in on_post
Traceback (most recent call last):
  File "/Users/user/Documents/workspace/KuaiSou/ks_cgi/handler.py", line 64, in on_post
    Content=google(Content)
  File "/Users/user/Documents/workspace/KuaiSou/ks_cgi/handler.py", line 47, in google
    search_results = urllib.urlopen(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 84, in urlopen
    return opener.open(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 205, in open
    return getattr(self, name)(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 342, in open_http
    h.endheaders(data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 951, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 811, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 773, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 754, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 553, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
IOError: [Errno socket error] [Errno 8] nodename nor servname provided, or not known
2012-12-26 22:02:20,282 - handler.py:108 - handler - ------------end--------------------


2012-12-26 22:11:17,654 - handler.py:21 - handler - ------------start--------------------

2012-12-26 22:11:17,655 - handler.py:31 - handler - POST on /scgi-bin/handler.py?signature=840e8ee35ef65dd598f1c5f249fa213801fdf6d4&timestamp=1356517202&nonce=1355917928
2012-12-26 22:11:17,655 - handler.py:60 - handler - raw:<xml><ToUserName><![CDATA[gh_1ff87fe87f88]]></ToUserName>
<FromUserName><![CDATA[oaEn2jhk1nCu9VREAmtTDufQd5kw]]></FromUserName>
<CreateTime>1356344005</CreateTime>
<MsgType><![CDATA[text]]></MsgType>
<Content><![CDATA[Northen JiaoTong]]></Content>
</xml>
2012-12-26 22:11:17,670 - handler.py:46 - handler - url:http://ajax.googleapis.com/ajax/services/search/web?v=1.0&q=Northen+JiaoTong&rsz=small
2012-12-26 22:11:17,704 - handler.py:83 - handler - exception in on_post
Traceback (most recent call last):
  File "/Users/user/Documents/workspace/KuaiSou/ks_cgi/handler.py", line 69, in on_post
    Content=google(Content)
  File "/Users/user/Documents/workspace/KuaiSou/ks_cgi/handler.py", line 53, in google
    search_results= urllib2.urlopen(req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 394, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 412, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 372, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1199, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1174, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 8] nodename nor servname provided, or not known>
2012-12-26 22:11:17,705 - handler.py:113 - handler - ------------end--------------------


2012-12-26 22:11:38,909 - handler.py:21 - handler - ------------start--------------------

2012-12-26 22:11:38,909 - handler.py:31 - handler - POST on /scgi-bin/handler.py?signature=840e8ee35ef65dd598f1c5f249fa213801fdf6d4&timestamp=1356517202&nonce=1355917928
2012-12-26 22:11:38,909 - handler.py:61 - handler - raw:<xml><ToUserName><![CDATA[gh_1ff87fe87f88]]></ToUserName>
<FromUserName><![CDATA[oaEn2jhk1nCu9VREAmtTDufQd5kw]]></FromUserName>
<CreateTime>1356344005</CreateTime>
<MsgType><![CDATA[text]]></MsgType>
<Content><![CDATA[Northen JiaoTong]]></Content>
</xml>
2012-12-26 22:11:39,042 - handler.py:46 - handler - url:http://ajax.googleapis.com/ajax/services/search/web?v=1.0&q=Northen+JiaoTong&rsz=small
2012-12-26 22:11:39,461 - handler.py:84 - handler - exception in on_post
Traceback (most recent call last):
  File "/Users/user/Documents/workspace/KuaiSou/ks_cgi/handler.py", line 70, in on_post
    Content=google(Content)
  File "/Users/user/Documents/workspace/KuaiSou/ks_cgi/handler.py", line 53, in google
    search_results= urllib2.urlopen(req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 394, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 412, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 372, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1199, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1174, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 8] nodename nor servname provided, or not known>
2012-12-26 22:11:39,462 - handler.py:114 - handler - ------------end--------------------


2012-12-26 22:12:08,980 - handler.py:21 - handler - ------------start--------------------

2012-12-26 22:12:08,980 - handler.py:31 - handler - POST on /scgi-bin/handler.py?signature=840e8ee35ef65dd598f1c5f249fa213801fdf6d4&timestamp=1356517202&nonce=1355917928
2012-12-26 22:12:08,981 - handler.py:62 - handler - raw:<xml><ToUserName><![CDATA[gh_1ff87fe87f88]]></ToUserName>
<FromUserName><![CDATA[oaEn2jhk1nCu9VREAmtTDufQd5kw]]></FromUserName>
<CreateTime>1356344005</CreateTime>
<MsgType><![CDATA[text]]></MsgType>
<Content><![CDATA[Northen JiaoTong]]></Content>
</xml>
2012-12-26 22:12:08,997 - handler.py:46 - handler - url:http://ajax.googleapis.com/ajax/services/search/web?v=1.0&q=Northen+JiaoTong&rsz=small
2012-12-26 22:12:08,998 - handler.py:53 - handler - req:<urllib2.Request instance at 0x105ec1950>
2012-12-26 22:12:09,019 - handler.py:85 - handler - exception in on_post
Traceback (most recent call last):
  File "/Users/user/Documents/workspace/KuaiSou/ks_cgi/handler.py", line 71, in on_post
    Content=google(Content)
  File "/Users/user/Documents/workspace/KuaiSou/ks_cgi/handler.py", line 54, in google
    search_results= urllib2.urlopen(req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 394, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 412, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 372, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1199, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1174, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 8] nodename nor servname provided, or not known>
2012-12-26 22:12:09,022 - handler.py:115 - handler - ------------end--------------------


2012-12-26 22:13:10,486 - handler.py:21 - handler - ------------start--------------------

2012-12-26 22:13:10,486 - handler.py:31 - handler - POST on /scgi-bin/handler.py?signature=840e8ee35ef65dd598f1c5f249fa213801fdf6d4&timestamp=1356517202&nonce=1355917928
2012-12-26 22:13:10,486 - handler.py:62 - handler - raw:<xml><ToUserName><![CDATA[gh_1ff87fe87f88]]></ToUserName>
<FromUserName><![CDATA[oaEn2jhk1nCu9VREAmtTDufQd5kw]]></FromUserName>
<CreateTime>1356344005</CreateTime>
<MsgType><![CDATA[text]]></MsgType>
<Content><![CDATA[Northen JiaoTong]]></Content>
</xml>
2012-12-26 22:13:10,502 - handler.py:46 - handler - url:http://ajax.googleapis.com/ajax/services/search/web?v=1.0&q=Northen+JiaoTong&rsz=small
2012-12-26 22:13:10,502 - handler.py:53 - handler - req:q=Northen+JiaoTong&rsz=small&v=1.0
2012-12-26 22:13:10,935 - handler.py:85 - handler - exception in on_post
Traceback (most recent call last):
  File "/Users/user/Documents/workspace/KuaiSou/ks_cgi/handler.py", line 71, in on_post
    Content=google(Content)
  File "/Users/user/Documents/workspace/KuaiSou/ks_cgi/handler.py", line 54, in google
    search_results= urllib2.urlopen(req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 394, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 412, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 372, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1199, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1174, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 8] nodename nor servname provided, or not known>
2012-12-26 22:13:10,936 - handler.py:115 - handler - ------------end--------------------


2012-12-26 22:14:45,838 - handler.py:21 - handler - ------------start--------------------

2012-12-26 22:14:45,838 - handler.py:31 - handler - POST on /scgi-bin/handler.py?signature=840e8ee35ef65dd598f1c5f249fa213801fdf6d4&timestamp=1356517202&nonce=1355917928
2012-12-26 22:14:45,839 - handler.py:62 - handler - raw:<xml><ToUserName><![CDATA[gh_1ff87fe87f88]]></ToUserName>
<FromUserName><![CDATA[oaEn2jhk1nCu9VREAmtTDufQd5kw]]></FromUserName>
<CreateTime>1356344005</CreateTime>
<MsgType><![CDATA[text]]></MsgType>
<Content><![CDATA[Northen JiaoTong]]></Content>
</xml>
2012-12-26 22:14:45,925 - handler.py:46 - handler - url:http://ajax.googleapis.com/ajax/services/search/web?v=1.0&q=Northen+JiaoTong&rsz=small
2012-12-26 22:14:45,926 - handler.py:53 - handler - req:q=Northen+JiaoTong&rsz=small&v=1.0
2012-12-26 22:14:46,342 - handler.py:85 - handler - exception in on_post
Traceback (most recent call last):
  File "/Users/user/Documents/workspace/KuaiSou/ks_cgi/handler.py", line 71, in on_post
    Content=google(Content)
  File "/Users/user/Documents/workspace/KuaiSou/ks_cgi/handler.py", line 54, in google
    search_results= urllib2.urlopen(req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 394, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 412, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 372, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1199, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1174, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 8] nodename nor servname provided, or not known>
2012-12-26 22:14:46,343 - handler.py:115 - handler - ------------end--------------------


2012-12-26 22:14:51,342 - handler.py:21 - handler - ------------start--------------------

2012-12-26 22:15:52,271 - handler.py:21 - handler - ------------start--------------------

2012-12-26 22:16:08,998 - ks_http.py:35 - handler - url:http://ajax.googleapis.com/ajax/services/search/web?v=1.0&q=abcdefg&rsz=small
2012-12-26 22:16:08,999 - ks_http.py:42 - handler - req:q=abcdefg&rsz=small&v=1.0
2012-12-26 22:16:35,869 - ks_http.py:35 - handler - url:http://ajax.googleapis.com/ajax/services/search/web?v=1.0&q=abcdefg&rsz=small
2012-12-26 22:16:35,875 - ks_http.py:42 - handler - req:q=abcdefg&rsz=small&v=1.0
2012-12-26 22:17:36,351 - ks_http.py:34 - handler - url:http://ajax.googleapis.com/ajax/services/search/web?v=1.0&q=abcdefg&rsz=small
2012-12-26 22:17:36,352 - ks_http.py:42 - handler - req:q=abcdefg&rsz=small&v=1.0
2012-12-26 22:17:54,048 - ks_http.py:34 - handler - url:http://ajax.googleapis.com/ajax/services/search/web?v=1.0&q=abcdefg&rsz=small
2012-12-26 22:17:54,114 - ks_http.py:42 - handler - req:q=abcdefg&rsz=small&v=1.0
2012-12-26 22:18:53,319 - ks_http.py:34 - handler - url:http://ajax.googleapis.com/ajax/services/search/web?v=1.0&q=abcdefg+%E5%A4%A7%E6%B1%97&rsz=small
2012-12-26 22:18:53,320 - ks_http.py:42 - handler - req:q=abcdefg+%E5%A4%A7%E6%B1%97&rsz=small&v=1.0
2012-12-26 22:19:29,363 - ks_http.py:34 - handler - url:http://ajax.googleapis.com/ajax/services/search/web?v=1.0&q=%E8%92%99%E5%8F%A4+%E5%A4%A7%E6%B1%97&rsz=small
2012-12-26 22:19:29,364 - ks_http.py:42 - handler - req:q=%E8%92%99%E5%8F%A4+%E5%A4%A7%E6%B1%97&rsz=small&v=1.0
2012-12-27 11:45:11,066 - handler.py:21 - handler - ------------start--------------------

2012-12-27 11:45:11,093 - handler.py:31 - handler - POST on /scgi-bin/handler.py?signature=840e8ee35ef65dd598f1c5f249fa213801fdf6d4&timestamp=1356517202&nonce=1355917928
2012-12-27 11:45:11,094 - handler.py:45 - handler - raw:<xml><ToUserName><![CDATA[gh_1ff87fe87f88]]></ToUserName>
<FromUserName><![CDATA[oaEn2jhk1nCu9VREAmtTDufQd5kw]]></FromUserName>
<CreateTime>1356344005</CreateTime>
<MsgType><![CDATA[text]]></MsgType>
<Content><![CDATA[大小]]></Content>
</xml>
2012-12-27 11:45:11,170 - ks_http.py:35 - handler - url:http://ajax.googleapis.com/ajax/services/search/web?v=1.0&q=%E5%A4%A7%E5%B0%8F&rsz=small
2012-12-27 11:45:11,483 - handler.py:56 - handler - {"responseData": {"results":[{"GsearchResultClass":"GwebSearch","unescapedUrl":"http://dxmonline.com/","url":"http://dxmonline.com/","visibleUrl":"dxmonline.com","cacheUrl":"http://www.google.com/search?q\u003dcache:8WY4SiO6rCIJ:dxmonline.com","title":"\u003cb\u003e大小\u003c/b\u003e創意- 繁體中文首頁","titleNoFormatting":"大小創意- 繁體中文首頁","content":"知名建築設計師/ \u003cb\u003e大小\u003c/b\u003e創意齋負責人姚仁祿先生，致力推動以創意為核心的價值觀。《  星空之下永遠有路》，收錄姚先生在《遠見》雜誌、《東方企業》雜誌、專題演講等文章 \u003cb\u003e...\u003c/b\u003e"},{"GsearchResultClass":"GwebSearch","unescapedUrl":"http://www.baike.com/wiki/%E5%A4%A7%E5%B0%8F","url":"http://www.baike.com/wiki/%25E5%25A4%25A7%25E5%25B0%258F","visibleUrl":"www.baike.com","cacheUrl":"http://www.google.com/search?q\u003dcache:eDzqGO9XlnMJ:www.baike.com","title":"\u003cb\u003e大小\u003c/b\u003e[汉语词典]_互动百科","titleNoFormatting":"大小[汉语词典]_互动百科","content":"\u003cb\u003e大小\u003c/b\u003e[汉语词典]-\u003cb\u003e大小\u003c/b\u003e拼音： dà xiǎo 解释： 1.大与小;大或小。 2.指尊卑或长幼。 3.谓  \u003cb\u003e大小\u003c/b\u003e的程度。 4.偏指大或小。 5.犹多少。引申指情况。"},{"GsearchResultClass":"GwebSearch","unescapedUrl":"http://www.2144.cn/html/28/11824/","url":"http://www.2144.cn/html/28/11824/","visibleUrl":"www.2144.cn","cacheUrl":"http://www.google.com/search?q\u003dcache:VJbgfpipzksJ:www.2144.cn","title":"\u003cb\u003e大小\u003c/b\u003e串串烧小游戏,在线玩,2144小游戏","titleNoFormatting":"大小串串烧小游戏,在线玩,2144小游戏","content":"\u003cb\u003e大小\u003c/b\u003e串串烧,游戏介绍：一个用竹签串食物的小游戏，用鼠标移动竹签，按住鼠标把竹  签推出去，连续串上3个或3个以上相同就能消除，要控制鼠标的力度哦，按住的时间 \u003cb\u003e...\u003c/b\u003e"},{"GsearchResultClass":"GwebSearch","unescapedUrl":"http://www.dxstudy.com/","url":"http://www.dxstudy.com/","visibleUrl":"www.dxstudy.com","cacheUrl":"http://www.google.com/search?q\u003dcache:2Tpbxi_vrzkJ:www.dxstudy.com","title":"\u003cb\u003e大小\u003c/b\u003e学习网-最专业的学习、教学资料下载站!","titleNoFormatting":"大小学习网-最专业的学习、教学资料下载站!","content":"\u003cb\u003e大小\u003c/b\u003e学习网专业的学习、教学资料下载站，包括课件、教案、试题的下载，更新速度快  。"}],"cursor":{"resultCount":"69,700,000","pages":[{"start":"0","label":1},{"start":"4","label":2},{"start":"8","label":3},{"start":"12","label":4},{"start":"16","label":5},{"start":"20","label":6},{"start":"24","label":7},{"start":"28","label":8}],"estimatedResultCount":"69700000","currentPageIndex":0,"moreResultsUrl":"http://www.google.com/search?oe\u003dutf8\u0026ie\u003dutf8\u0026source\u003duds\u0026start\u003d0\u0026hl\u003den\u0026q\u003d%E5%A4%A7%E5%B0%8F","searchResultTime":"0.17"}}, "responseDetails": null, "responseStatus": 200}
2012-12-27 11:45:11,483 - handler.py:66 - handler - response:<xml>
                            <ToUserName><![CDATA[oaEn2jhk1nCu9VREAmtTDufQd5kw]]></ToUserName>
                            <FromUserName><![CDATA[gh_1ff87fe87f88]]></FromUserName>
                            <CreateTime>1356579911.48</CreateTime>
                            <MsgType><![CDATA[text]]></MsgType>
                            <Content><![CDATA[{"responseData": {"results":[{"GsearchResultClass":"GwebSearch","unescapedUrl":"http://dxmonline.com/","url":"http://dxmonline.com/","visibleUrl":"dxmonline.com","cacheUrl":"http://www.google.com/search?q\u003dcache:8WY4SiO6rCIJ:dxmonline.com","title":"\u003cb\u003e大小\u003c/b\u003e創意- 繁體中文首頁","titleNoFormatting":"大小創意- 繁體中文首頁","content":"知名建築設計師/ \u003cb\u003e大小\u003c/b\u003e創意齋負責人姚仁祿先生，致力推動以創意為核心的價值觀。《  星空之下永遠有路》，收錄姚先生在《遠見》雜誌、《東方企業》雜誌、專題演講等文章 \u003cb\u003e...\u003c/b\u003e"},{"GsearchResultClass":"GwebSearch","unescapedUrl":"http://www.baike.com/wiki/%E5%A4%A7%E5%B0%8F","url":"http://www.baike.com/wiki/%25E5%25A4%25A7%25E5%25B0%258F","visibleUrl":"www.baike.com","cacheUrl":"http://www.google.com/search?q\u003dcache:eDzqGO9XlnMJ:www.baike.com","title":"\u003cb\u003e大小\u003c/b\u003e[汉语词典]_互动百科","titleNoFormatting":"大小[汉语词典]_互动百科","content":"\u003cb\u003e大小\u003c/b\u003e[汉语词典]-\u003cb\u003e大小\u003c/b\u003e拼音： dà xiǎo 解释： 1.大与小;大或小。 2.指尊卑或长幼。 3.谓  \u003cb\u003e大小\u003c/b\u003e的程度。 4.偏指大或小。 5.犹多少。引申指情况。"},{"GsearchResultClass":"GwebSearch","unescapedUrl":"http://www.2144.cn/html/28/11824/","url":"http://www.2144.cn/html/28/11824/","visibleUrl":"www.2144.cn","cacheUrl":"http://www.google.com/search?q\u003dcache:VJbgfpipzksJ:www.2144.cn","title":"\u003cb\u003e大小\u003c/b\u003e串串烧小游戏,在线玩,2144小游戏","titleNoFormatting":"大小串串烧小游戏,在线玩,2144小游戏","content":"\u003cb\u003e大小\u003c/b\u003e串串烧,游戏介绍：一个用竹签串食物的小游戏，用鼠标移动竹签，按住鼠标把竹  签推出去，连续串上3个或3个以上相同就能消除，要控制鼠标的力度哦，按住的时间 \u003cb\u003e...\u003c/b\u003e"},{"GsearchResultClass":"GwebSearch","unescapedUrl":"http://www.dxstudy.com/","url":"http://www.dxstudy.com/","visibleUrl":"www.dxstudy.com","cacheUrl":"http://www.google.com/search?q\u003dcache:2Tpbxi_vrzkJ:www.dxstudy.com","title":"\u003cb\u003e大小\u003c/b\u003e学习网-最专业的学习、教学资料下载站!","titleNoFormatting":"大小学习网-最专业的学习、教学资料下载站!","content":"\u003cb\u003e大小\u003c/b\u003e学习网专业的学习、教学资料下载站，包括课件、教案、试题的下载，更新速度快  。"}],"cursor":{"resultCount":"69,700,000","pages":[{"start":"0","label":1},{"start":"4","label":2},{"start":"8","label":3},{"start":"12","label":4},{"start":"16","label":5},{"start":"20","label":6},{"start":"24","label":7},{"start":"28","label":8}],"estimatedResultCount":"69700000","currentPageIndex":0,"moreResultsUrl":"http://www.google.com/search?oe\u003dutf8\u0026ie\u003dutf8\u0026source\u003duds\u0026start\u003d0\u0026hl\u003den\u0026q\u003d%E5%A4%A7%E5%B0%8F","searchResultTime":"0.17"}}, "responseDetails": null, "responseStatus": 200}]]></Content>
                            <FuncFlag>0</FuncFlag>
                            </xml>
2012-12-27 11:45:11,483 - handler.py:71 - handler - exception in on_post
Traceback (most recent call last):
  File "/Users/user/Documents/workspace/KuaiSou/ks_cgi/handler.py", line 68, in on_post
    sys.stdout = codecs.getwriter('utf-8')(sys.stdout, 'strict')
NameError: global name 'codecs' is not defined
2012-12-27 11:45:11,484 - handler.py:96 - handler - ------------end--------------------


2012-12-27 16:45:30,091 - handler.py:21 - handler - ------------start--------------------

2012-12-27 16:45:30,091 - handler.py:31 - handler - POST on /scgi-bin/handler.py?signature=840e8ee35ef65dd598f1c5f249fa213801fdf6d4&timestamp=1356517202&nonce=1355917928
2012-12-27 16:45:30,091 - handler.py:45 - handler - raw:<xml><ToUserName><![CDATA[gh_1ff87fe87f88]]></ToUserName>
<FromUserName><![CDATA[oaEn2jhk1nCu9VREAmtTDufQd5kw]]></FromUserName>
<CreateTime>1356344005</CreateTime>
<MsgType><![CDATA[text]]></MsgType>
<Content><![CDATA[大小]]></Content>
</xml>
2012-12-27 16:45:30,135 - ks_http.py:35 - handler - url:http://ajax.googleapis.com/ajax/services/search/web?v=1.0&q=%E5%A4%A7%E5%B0%8F&rsz=small
2012-12-27 16:45:30,353 - handler.py:56 - handler - [{'GsearchResultClass': 'GwebSearch', 'visibleUrl': 'dxmonline.com', 'titleNoFormatting': u'\u5927\u5c0f\u5275\u610f- \u7e41\u9ad4\u4e2d\u6587\u9996\u9801', 'title': u'<b>\u5927\u5c0f</b>\u5275\u610f- \u7e41\u9ad4\u4e2d\u6587\u9996\u9801', 'url': 'http://dxmonline.com/', 'cacheUrl': 'http://www.google.com/search?q=cache:8WY4SiO6rCIJ:dxmonline.com', 'unescapedUrl': 'http://dxmonline.com/', 'content': u'\u77e5\u540d\u5efa\u7bc9\u8a2d\u8a08\u5e2b/ <b>\u5927\u5c0f</b>\u5275\u610f\u9f4b\u8ca0\u8cac\u4eba\u59da\u4ec1\u797f\u5148\u751f\uff0c\u81f4\u529b\u63a8\u52d5\u4ee5\u5275\u610f\u70ba\u6838\u5fc3\u7684\u50f9\u503c\u89c0\u3002\u300a  \u661f\u7a7a\u4e4b\u4e0b\u6c38\u9060\u6709\u8def\u300b\uff0c\u6536\u9304\u59da\u5148\u751f\u5728\u300a\u9060\u898b\u300b\u96dc\u8a8c\u3001\u300a\u6771\u65b9\u4f01\u696d\u300b\u96dc\u8a8c\u3001\u5c08\u984c\u6f14\u8b1b\u7b49\u6587\u7ae0 <b>...</b>'}, {'GsearchResultClass': 'GwebSearch', 'visibleUrl': 'www.baike.com', 'titleNoFormatting': u'\u5927\u5c0f[\u6c49\u8bed\u8bcd\u5178]_\u4e92\u52a8\u767e\u79d1', 'title': u'<b>\u5927\u5c0f</b>[\u6c49\u8bed\u8bcd\u5178]_\u4e92\u52a8\u767e\u79d1', 'url': 'http://www.baike.com/wiki/%25E5%25A4%25A7%25E5%25B0%258F', 'cacheUrl': 'http://www.google.com/search?q=cache:eDzqGO9XlnMJ:www.baike.com', 'unescapedUrl': 'http://www.baike.com/wiki/%E5%A4%A7%E5%B0%8F', 'content': u'<b>\u5927\u5c0f</b>[\u6c49\u8bed\u8bcd\u5178]-<b>\u5927\u5c0f</b>\u62fc\u97f3\uff1a d\xe0 xi\u01ceo \u89e3\u91ca\uff1a 1.\u5927\u4e0e\u5c0f;\u5927\u6216\u5c0f\u3002 2.\u6307\u5c0a\u5351\u6216\u957f\u5e7c\u3002 3.\u8c13  <b>\u5927\u5c0f</b>\u7684\u7a0b\u5ea6\u3002 4.\u504f\u6307\u5927\u6216\u5c0f\u3002 5.\u72b9\u591a\u5c11\u3002\u5f15\u7533\u6307\u60c5\u51b5\u3002'}, {'GsearchResultClass': 'GwebSearch', 'visibleUrl': 'www.2144.cn', 'titleNoFormatting': u'\u5927\u5c0f\u4e32\u4e32\u70e7\u5c0f\u6e38\u620f,\u5728\u7ebf\u73a9,2144\u5c0f\u6e38\u620f', 'title': u'<b>\u5927\u5c0f</b>\u4e32\u4e32\u70e7\u5c0f\u6e38\u620f,\u5728\u7ebf\u73a9,2144\u5c0f\u6e38\u620f', 'url': 'http://www.2144.cn/html/28/11824/', 'cacheUrl': 'http://www.google.com/search?q=cache:VJbgfpipzksJ:www.2144.cn', 'unescapedUrl': 'http://www.2144.cn/html/28/11824/', 'content': u'<b>\u5927\u5c0f</b>\u4e32\u4e32\u70e7,\u6e38\u620f\u4ecb\u7ecd\uff1a\u4e00\u4e2a\u7528\u7af9\u7b7e\u4e32\u98df\u7269\u7684\u5c0f\u6e38\u620f\uff0c\u7528\u9f20\u6807\u79fb\u52a8\u7af9\u7b7e\uff0c\u6309\u4f4f\u9f20\u6807\u628a\u7af9  \u7b7e\u63a8\u51fa\u53bb\uff0c\u8fde\u7eed\u4e32\u4e0a3\u4e2a\u62163\u4e2a\u4ee5\u4e0a\u76f8\u540c\u5c31\u80fd\u6d88\u9664\uff0c\u8981\u63a7\u5236\u9f20\u6807\u7684\u529b\u5ea6\u54e6\uff0c\u6309\u4f4f\u7684\u65f6\u95f4 <b>...</b>'}, {'GsearchResultClass': 'GwebSearch', 'visibleUrl': 'www.dxstudy.com', 'titleNoFormatting': u'\u5927\u5c0f\u5b66\u4e60\u7f51-\u6700\u4e13\u4e1a\u7684\u5b66\u4e60\u3001\u6559\u5b66\u8d44\u6599\u4e0b\u8f7d\u7ad9!', 'title': u'<b>\u5927\u5c0f</b>\u5b66\u4e60\u7f51-\u6700\u4e13\u4e1a\u7684\u5b66\u4e60\u3001\u6559\u5b66\u8d44\u6599\u4e0b\u8f7d\u7ad9!', 'url': 'http://www.dxstudy.com/', 'cacheUrl': 'http://www.google.com/search?q=cache:2Tpbxi_vrzkJ:www.dxstudy.com', 'unescapedUrl': 'http://www.dxstudy.com/', 'content': u'<b>\u5927\u5c0f</b>\u5b66\u4e60\u7f51\u4e13\u4e1a\u7684\u5b66\u4e60\u3001\u6559\u5b66\u8d44\u6599\u4e0b\u8f7d\u7ad9\uff0c\u5305\u62ec\u8bfe\u4ef6\u3001\u6559\u6848\u3001\u8bd5\u9898\u7684\u4e0b\u8f7d\uff0c\u66f4\u65b0\u901f\u5ea6\u5feb  \u3002'}]
2012-12-27 16:45:30,353 - handler.py:70 - handler - exception in on_post
Traceback (most recent call last):
  File "/Users/user/Documents/workspace/KuaiSou/ks_cgi/handler.py", line 64, in on_post
    </xml>"""%(FromUserName,ToUserName,time.time(),"text",Content.decode('utf-8').encode('ascii','ignore'))
AttributeError: 'list' object has no attribute 'decode'
2012-12-27 16:45:30,353 - handler.py:95 - handler - ------------end--------------------


2012-12-28 16:39:26,055 - handler.py:21 - handler - ------------start--------------------

2012-12-28 16:39:26,066 - handler.py:31 - handler - POST on /scgi-bin/handler.py?signature=840e8ee35ef65dd598f1c5f249fa213801fdf6d4&timestamp=1356517202&nonce=1355917928
2012-12-28 16:39:26,066 - handler.py:45 - handler - raw:<xml><ToUserName><![CDATA[gh_1ff87fe87f88]]></ToUserName>
<FromUserName><![CDATA[oaEn2jhk1nCu9VREAmtTDufQd5kw]]></FromUserName>
<CreateTime>1356344005</CreateTime>
<MsgType><![CDATA[text]]></MsgType>
<Content><![CDATA[大小]]></Content>
</xml>
2012-12-28 16:39:26,130 - handler.py:71 - handler - response:<xml>
                            <ToUserName><![CDATA[oaEn2jhk1nCu9VREAmtTDufQd5kw]]></ToUserName>
                            <FromUserName><![CDATA[gh_1ff87fe87f88]]></FromUserName>
                            <CreateTime>1356683966.12</CreateTime>
                            <MsgType><![CDATA[location]]></MsgType>
                            <Location_X>22.617716</Location_X>
                            <Location_Y>114.057151</Location_Y>
                            <FuncFlag>0</FuncFlag>
                            </xml>
2012-12-28 16:39:26,130 - handler.py:100 - handler - ------------end--------------------


2012-12-29 15:07:02,923 - handler.py:21 - handler - ------------start--------------------

2012-12-29 15:07:02,941 - handler.py:31 - handler - POST on /scgi-bin/handler.py?signature=840e8ee35ef65dd598f1c5f249fa213801fdf6d4&timestamp=1356517202&nonce=1355917928
2012-12-29 15:07:02,941 - handler.py:76 - handler - raw:<xml><ToUserName><![CDATA[gh_1ff87fe87f88]]></ToUserName>
<FromUserName><![CDATA[oaEn2jhk1nCu9VREAmtTDufQd5kw]]></FromUserName>
<CreateTime>1356344005</CreateTime>
<MsgType><![CDATA[text]]></MsgType>
<Content><![CDATA[大小]]></Content>
</xml>
2012-12-29 15:07:03,008 - ks_http.py:35 - handler - url:http://ajax.googleapis.com/ajax/services/search/web?v=1.0&q=%E5%A4%A7%E5%B0%8F&rsz=small
2012-12-29 15:07:03,114 - handler.py:109 - handler - exception in on_post
Traceback (most recent call last):
  File "/Users/user/Documents/workspace/KuaiSou/ks_cgi/handler.py", line 86, in on_post
    content=handler(doc)
  File "/Users/user/Documents/workspace/KuaiSou/ks_cgi/handler.py", line 43, in on_text_msg
    Content=ks_http.google(Content)
  File "/Users/user/Documents/workspace/KuaiSou/ks_cgi/ks_http.py", line 49, in google
    search_results = urllib.urlopen(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 84, in urlopen
    return opener.open(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 205, in open
    return getattr(self, name)(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 342, in open_http
    h.endheaders(data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 951, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 811, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 773, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 754, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 571, in create_connection
    raise err
IOError: [Errno socket error] [Errno 61] Connection refused
2012-12-29 15:07:03,171 - handler.py:134 - handler - ------------end--------------------


2012-12-30 14:54:42,386 - ks_http.py:35 - handler - url:http://ajax.googleapis.com/ajax/services/search/web?v=1.0&q=%E8%92%99%E5%8F%A4+%E5%A4%A7%E6%B1%97&rsz=large
2012-12-30 21:53:30,105 - handler.py:22 - handler - ------------start--------------------

2012-12-30 21:53:30,105 - handler.py:32 - handler - POST on /scgi-bin/handler.py?signature=840e8ee35ef65dd598f1c5f249fa213801fdf6d4&timestamp=1356517202&nonce=1355917928
2012-12-30 21:53:30,105 - handler.py:102 - handler - raw:<xml><ToUserName><![CDATA[gh_1ff87fe87f88]]></ToUserName>
<FromUserName><![CDATA[oaEn2jhk1nCu9VREAmtTDufQd5kw]]></FromUserName>
<CreateTime>1356344005</CreateTime>
<MsgType><![CDATA[text]]></MsgType>
<Content><![CDATA[大小]]></Content>
</xml>
2012-12-30 21:53:30,268 - handler.py:58 - handler - request content length:2
2012-12-30 21:53:30,268 - ks_http.py:48 - handler - url:http://ajax.googleapis.com/ajax/services/search/web?v=1.0&q=%E5%A4%A7%E5%B0%8F&rsz=large
2012-12-30 21:53:30,526 - handler.py:135 - handler - exception in on_post
Traceback (most recent call last):
  File "/Users/user/Documents/workspace/KuaiSoo/ks_cgi/handler.py", line 112, in on_post
    content=handler(doc)
  File "/Users/user/Documents/workspace/KuaiSoo/ks_cgi/handler.py", line 69, in on_text_msg
    Content=ks_http.google(Content)
  File "/Users/user/Documents/workspace/KuaiSoo/ks_cgi/ks_http.py", line 62, in google
    search_results = urllib.urlopen(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 84, in urlopen
    return opener.open(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 205, in open
    return getattr(self, name)(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 342, in open_http
    h.endheaders(data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 951, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 811, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 773, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 754, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 571, in create_connection
    raise err
IOError: [Errno socket error] [Errno 61] Connection refused
2012-12-30 21:53:30,587 - handler.py:160 - handler - ------------end--------------------


2012-12-30 21:53:49,596 - handler.py:22 - handler - ------------start--------------------

2012-12-30 21:53:49,610 - handler.py:32 - handler - POST on /scgi-bin/handler.py?signature=840e8ee35ef65dd598f1c5f249fa213801fdf6d4&timestamp=1356517202&nonce=1355917928
2012-12-30 21:53:49,610 - handler.py:102 - handler - raw:<xml><ToUserName><![CDATA[gh_1ff87fe87f88]]></ToUserName>
<FromUserName><![CDATA[oaEn2jhk1nCu9VREAmtTDufQd5kw]]></FromUserName>
<CreateTime>1356344005</CreateTime>
<MsgType><![CDATA[text]]></MsgType>
<Content><![CDATA[大小]]></Content>
</xml>
2012-12-30 21:53:49,634 - handler.py:58 - handler - request content length:2
2012-12-30 21:53:49,635 - ks_http.py:48 - handler - url:http://ajax.googleapis.com/ajax/services/search/web?v=1.0&q=%E5%A4%A7%E5%B0%8F&rsz=large
2012-12-30 21:54:25,988 - handler.py:135 - handler - exception in on_post
Traceback (most recent call last):
  File "/Users/user/Documents/workspace/KuaiSoo/ks_cgi/handler.py", line 112, in on_post
    content=handler(doc)
  File "/Users/user/Documents/workspace/KuaiSoo/ks_cgi/handler.py", line 69, in on_text_msg
    Content=ks_http.google(Content)
  File "/Users/user/Documents/workspace/KuaiSoo/ks_cgi/ks_http.py", line 62, in google
    search_results = urllib.urlopen(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 84, in urlopen
    return opener.open(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 205, in open
    return getattr(self, name)(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 342, in open_http
    h.endheaders(data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 951, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 811, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 773, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 754, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 571, in create_connection
    raise err
IOError: [Errno socket error] [Errno 61] Connection refused
2012-12-30 21:54:25,990 - handler.py:160 - handler - ------------end--------------------


2012-12-30 21:54:32,173 - handler.py:22 - handler - ------------start--------------------

2012-12-30 21:54:32,174 - handler.py:32 - handler - POST on /scgi-bin/handler.py?signature=840e8ee35ef65dd598f1c5f249fa213801fdf6d4&timestamp=1356517202&nonce=1355917928
2012-12-30 21:54:32,174 - handler.py:102 - handler - raw:<xml><ToUserName><![CDATA[gh_1ff87fe87f88]]></ToUserName>
<FromUserName><![CDATA[oaEn2jhk1nCu9VREAmtTDufQd5kw]]></FromUserName>
<CreateTime>1356344005</CreateTime>
<MsgType><![CDATA[text]]></MsgType>
<Content><![CDATA[大小]]></Content>
</xml>
2012-12-30 21:54:32,205 - handler.py:58 - handler - request content length:2
2012-12-30 21:54:32,205 - ks_http.py:48 - handler - url:http://ajax.googleapis.com/ajax/services/search/web?v=1.0&q=%E5%A4%A7%E5%B0%8F&rsz=large
2012-12-30 21:54:32,263 - handler.py:135 - handler - exception in on_post
Traceback (most recent call last):
  File "/Users/user/Documents/workspace/KuaiSoo/ks_cgi/handler.py", line 112, in on_post
    content=handler(doc)
  File "/Users/user/Documents/workspace/KuaiSoo/ks_cgi/handler.py", line 69, in on_text_msg
    Content=ks_http.google(Content)
  File "/Users/user/Documents/workspace/KuaiSoo/ks_cgi/ks_http.py", line 62, in google
    search_results = urllib.urlopen(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 84, in urlopen
    return opener.open(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 205, in open
    return getattr(self, name)(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 342, in open_http
    h.endheaders(data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 951, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 811, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 773, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 754, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 571, in create_connection
    raise err
IOError: [Errno socket error] [Errno 61] Connection refused
2012-12-30 21:54:32,265 - handler.py:160 - handler - ------------end--------------------


2012-12-30 21:54:41,736 - handler.py:22 - handler - ------------start--------------------

2012-12-30 21:54:41,736 - handler.py:32 - handler - POST on /scgi-bin/handler.py?signature=840e8ee35ef65dd598f1c5f249fa213801fdf6d4&timestamp=1356517202&nonce=1355917928
2012-12-30 21:54:41,736 - handler.py:102 - handler - raw:<xml><ToUserName><![CDATA[gh_1ff87fe87f88]]></ToUserName>
<FromUserName><![CDATA[oaEn2jhk1nCu9VREAmtTDufQd5kw]]></FromUserName>
<CreateTime>1356344005</CreateTime>
<MsgType><![CDATA[text]]></MsgType>
<Content><![CDATA[大小]]></Content>
</xml>
2012-12-30 21:54:41,785 - handler.py:58 - handler - request content length:2
2012-12-30 21:54:41,785 - ks_http.py:48 - handler - url:http://ajax.googleapis.com/ajax/services/search/web?v=1.0&q=%E5%A4%A7%E5%B0%8F&rsz=large
2012-12-30 21:54:41,888 - handler.py:135 - handler - exception in on_post
Traceback (most recent call last):
  File "/Users/user/Documents/workspace/KuaiSoo/ks_cgi/handler.py", line 112, in on_post
    content=handler(doc)
  File "/Users/user/Documents/workspace/KuaiSoo/ks_cgi/handler.py", line 69, in on_text_msg
    Content=ks_http.google(Content)
  File "/Users/user/Documents/workspace/KuaiSoo/ks_cgi/ks_http.py", line 62, in google
    search_results = urllib.urlopen(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 84, in urlopen
    return opener.open(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 205, in open
    return getattr(self, name)(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 342, in open_http
    h.endheaders(data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 951, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 811, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 773, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 754, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 571, in create_connection
    raise err
IOError: [Errno socket error] [Errno 61] Connection refused
2012-12-30 21:54:41,890 - handler.py:160 - handler - ------------end--------------------


